name: Release Pipeline

on:
  release:
    types:
      - created
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  regression-tests:
    needs: build

    runs-on: ubuntu-latest
    steps:
        - name: Run Cucumber Regression
          uses: greffgreff/run-java-tests-action@1.0
          with:
            repo: https://github.com/UIMA-Messaging/uima-test-suite.git
            branch: master
  
  docker:
    needs: regression-tests
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dockeroo80/uima-auth-service
          tags: ${{ github.ref_name }}
          registry: docker.io
          dockerfile: Dockerfile
          username: dockeroo80
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          
  deploy:
    needs: docker
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate kube configuration
        run: |
          mkdir ~/.kube
          touch ~/.kube/config
          echo "${{ secrets.AKS_CONTEXT }}" >> ~/.kube/config
      - name: Deploy application
        run: |
          sed -e 's|IMAGE_TAG|${{ github.ref_name }}|g' k8s/deployment.yml | kubectl apply -f -
      - name: Restart pod
        run: kubectl rollout restart deploy auth-app
